<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="STPAsec" nsURI="http://www.example.org/STPAsec" nsPrefix="STPAsec">
  <eClassifiers xsi:type="ecore:EClass" name="STPASec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systems" upperBound="-1"
        eType="#//System" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystems" upperBound="-1"
        eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemMode" upperBound="-1"
        eType="#//ControlStructure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlStructure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelGoal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlledprocess" upperBound="-1"
        eType="#//ControlledProcess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlaction" upperBound="-1"
        eType="#//ControlAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedback" upperBound="-1"
        eType="#//Feedback" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendsFeedbacks" eType="#//Feedback"
        eOpposite="#//Feedback/controllerFeedbackReceiver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendsCommands" eType="#//ControlAction"
        eOpposite="#//ControlAction/controllerCommandReceiver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllerSendsInfo" upperBound="-1"
        eType="#//OtherInformation" eOpposite="#//OtherInformation/ccontrollerReceiverInfo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" upperBound="-1"
        eType="#//System"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlStructureElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlledProcess" eSuperTypes="#//ControlStructureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendsFeedbacks" eType="#//Feedback"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controledProcessSendsInfo"
        upperBound="-1" eType="#//OtherInformation" eOpposite="#//OtherInformation/ControledProcessRecevierInfo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlAction" eSuperTypes="#//ControlStructureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllerCommandReceiver"
        upperBound="-1" eType="#//ControlStructure" eOpposite="#//ControlStructure/sendsCommands"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controledProccessReceiverCommands"
        eType="#//ControlledProcess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feedback" eSuperTypes="#//ControlStructureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllerFeedbackReceiver"
        upperBound="-1" eType="#//ControlStructure" eOpposite="#//ControlStructure/sendsFeedbacks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OtherInformation" eSuperTypes="#//ControlStructureElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ccontrollerReceiverInfo"
        upperBound="-1" eType="#//ControlStructure" eOpposite="#//ControlStructure/controllerSendsInfo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControledProcessRecevierInfo"
        eType="#//ControlledProcess" eOpposite="#//ControlledProcess/controledProcessSendsInfo"/>
  </eClassifiers>
</ecore:EPackage>
